/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;
import java.awt.GridLayout;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class AdminSchedule extends javax.swing.JFrame {

    /**
     * Creates new form AdminSchedule
     */
    public AdminSchedule() {
        initComponents();
        schedule.loadGames();
        fillTable();
    }
    Homepage homeP = new Homepage();
    Schedule schedule = new Schedule();

    public void fillTable()
    {
        //store the game info and columns in arrays
        String columns[] = {"Date", "Time", "Teams (Home vs Away)", "Tickets"};
        
        ArrayList<Game> games = schedule.getGames();
        
        //put all the games into a 2D array
        int rows = games.size();
        Object sched[][] = new Object[rows][4];
        
        for (int i = 0; i < rows; i++)
        {
            for (int j = 0; j < 4; j++)
            {
                if (j == 0)
                    sched[i][j] = Integer.toString(games.get(i).date);
                else if (j == 1)
                    sched[i][j] = Integer.toString(games.get(i).time);
                else if (j == 2)
                    sched[i][j] = games.get(i).getName();
                else
                    sched[i][j] = "View Tickets";
            }
        }
        
        //update the table. use this approach with sorting
        DefaultTableModel model = new DefaultTableModel(sched, columns);
        scheduleTable.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoLbl1 = new javax.swing.JLabel();
        homepageBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        sortDateBtn = new javax.swing.JButton();
        addGameBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();
        cancelGameBtn1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bannerPanel.setBackground(new java.awt.Color(0, 51, 102));
        bannerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SoftwareCreationNation");

        homepageBtn.setBackground(new java.awt.Color(204, 204, 204));
        homepageBtn.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        homepageBtn.setForeground(new java.awt.Color(255, 255, 255));
        homepageBtn.setText("Homepage");
        homepageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        homepageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoLbl1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 899, Short.MAX_VALUE)
                .addComponent(homepageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addGroup(bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bannerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLbl1))
                    .addGroup(bannerPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(bannerPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(homepageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        sortDateBtn.setBackground(new java.awt.Color(204, 204, 204));
        sortDateBtn.setForeground(new java.awt.Color(0, 51, 102));
        sortDateBtn.setText("Sort by Date");
        sortDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortDateBtnActionPerformed(evt);
            }
        });

        addGameBtn.setBackground(new java.awt.Color(204, 204, 204));
        addGameBtn.setForeground(new java.awt.Color(0, 51, 102));
        addGameBtn.setText("Add Game");
        addGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addGameBtnActionPerformed(evt);
            }
        });

        scheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Time", "Teams (Home vs Away)"
            }
        ));
        scheduleTable.setRowHeight(50);
        jScrollPane1.setViewportView(scheduleTable);

        cancelGameBtn1.setBackground(new java.awt.Color(204, 204, 204));
        cancelGameBtn1.setForeground(new java.awt.Color(0, 51, 102));
        cancelGameBtn1.setText("Cancel Game");
        cancelGameBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelGameBtn1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1327, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(sortDateBtn)
                        .addGap(37, 37, 37)
                        .addComponent(cancelGameBtn1)
                        .addGap(35, 35, 35)
                        .addComponent(addGameBtn)))
                .addGap(19, 19, 19))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addGameBtn)
                    .addComponent(sortDateBtn)
                    .addComponent(cancelGameBtn1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bannerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homepageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageBtnActionPerformed
        // TODO add your handling code here:
        AdminSignedInHomepage adminHome = new AdminSignedInHomepage();
        adminHome.setVisible(rootPaneCheckingEnabled);
        setVisible(false);
    }//GEN-LAST:event_homepageBtnActionPerformed

    private void sortDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortDateBtnActionPerformed
        // call the sorting method for sort by date and reload the table
        schedule.sortedSchedule();
        fillTable();
    }//GEN-LAST:event_sortDateBtnActionPerformed

    private void addGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addGameBtnActionPerformed
        // admin can add a game via a pop-up panel
        JTextField date = new JTextField();
        JTextField time = new JTextField();
        JTextField teams = new JTextField();
        
        JPanel addGamePanel = new JPanel(new GridLayout(0, 1));
        
        addGamePanel.add(new JLabel("Date of Game"));
        addGamePanel.add(date);
        addGamePanel.add(new JLabel("Time of Game"));
        addGamePanel.add(time);
        addGamePanel.add(new JLabel("Teams (Home vs Away)"));
        addGamePanel.add(teams);
        
        JOptionPane.showConfirmDialog(null, addGamePanel, "Update Schedule", 
        JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        
        String dateInfo = date.getText();
        String timeInfo = time.getText();
        String teamInfo = teams.getText();
        
        //create a new game
        Game newGame;
        try {
            newGame = new Game(1, teamInfo, Integer.parseInt(dateInfo), Integer.parseInt(timeInfo));
        } catch (SQLException ex) {
            Logger.getLogger(AdminSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        //add the game to the schedule
        schedule.addGame(teamInfo, Integer.parseInt(dateInfo), Integer.parseInt(timeInfo), 5, 5, 10, 10, 20, 15, 10, 10);
        
        //update the schedule
        fillTable();
    }//GEN-LAST:event_addGameBtnActionPerformed

    private void cancelGameBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelGameBtn1ActionPerformed
        try {
            // TODO add your handling code here:
            // admin can cancel a game via a pop-up panel
            JTextField game_id = new JTextField();
            
            JPanel cancelGamePanel = new JPanel(new GridLayout(0, 1));
            
            cancelGamePanel.add(new JLabel("Game ID"));
            cancelGamePanel.add(game_id);
            
            JOptionPane.showConfirmDialog(null, cancelGamePanel, "Cancel Game",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            
            String game_id_info = game_id.getText();
            
            //cancel a game
            Admin admin = new Admin(Integer.parseInt(game_id_info));
            admin.cancelGame(Integer.parseInt(game_id_info));
            
            //update the schedule
            fillTable();
        } catch (SQLException ex) {
            Logger.getLogger(AdminSchedule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cancelGameBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSchedule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSchedule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addGameBtn;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JButton cancelGameBtn1;
    private javax.swing.JButton homepageBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLbl1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable scheduleTable;
    private javax.swing.JButton sortDateBtn;
    // End of variables declaration//GEN-END:variables
}
