/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * This page allows the admin to update the seats of the data base
 */
public class AdminSeating extends javax.swing.JFrame {
    
    private String gameId;
    private String seatId;
    private String section;
    private String price;
    private String status;

    /**
     * Creates new form AdminSeating
     */
    public AdminSeating() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner = new javax.swing.JPanel();
        creationNation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        updateSeatsPanel = new javax.swing.JPanel();
        updateSeatsLabel = new javax.swing.JLabel();
        updateButton = new javax.swing.JButton();
        gameIDLabel = new javax.swing.JLabel();
        seatIDLabel = new javax.swing.JLabel();
        sectionLabel = new javax.swing.JLabel();
        priceID = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        gameIDText = new javax.swing.JTextField();
        seatIDText = new javax.swing.JTextField();
        sectionText = new javax.swing.JTextField();
        priceText = new javax.swing.JTextField();
        statusText = new javax.swing.JTextField();
        errorMsg = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1110, 700));
        setSize(new java.awt.Dimension(1110, 700));

        banner.setBackground(new java.awt.Color(8, 52, 108));

        creationNation.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        creationNation.setForeground(new java.awt.Color(255, 255, 255));
        creationNation.setText("SoftwareCreationNation");

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/helentran/NetBeansProjects/GameArenaSys/Images/LogoBanner.png")); // NOI18N

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(creationNation)
                .addContainerGap(743, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bannerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(creationNation)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        updateSeatsPanel.setBackground(new java.awt.Color(255, 255, 255));
        updateSeatsPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        updateSeatsLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        updateSeatsLabel.setText("Update Seats");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        gameIDLabel.setText("GameID:");

        seatIDLabel.setText("SeatID:");

        sectionLabel.setText("Section:");

        priceID.setText("Price");

        statusLabel.setText("Status:");

        errorMsg.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout updateSeatsPanelLayout = new javax.swing.GroupLayout(updateSeatsPanel);
        updateSeatsPanel.setLayout(updateSeatsPanelLayout);
        updateSeatsPanelLayout.setHorizontalGroup(
            updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, updateSeatsPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(25, 25, 25))
            .addGroup(updateSeatsPanelLayout.createSequentialGroup()
                .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(updateSeatsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(updateSeatsLabel))
                    .addGroup(updateSeatsPanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gameIDLabel)
                            .addComponent(seatIDLabel)
                            .addComponent(sectionLabel)
                            .addComponent(priceID)
                            .addComponent(statusLabel))
                        .addGap(65, 65, 65)
                        .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(gameIDText)
                                .addComponent(seatIDText)
                                .addComponent(sectionText)
                                .addComponent(statusText)
                                .addComponent(priceText, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        updateSeatsPanelLayout.setVerticalGroup(
            updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateSeatsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(updateSeatsLabel)
                .addGap(3, 3, 3)
                .addComponent(errorMsg)
                .addGap(18, 18, 18)
                .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gameIDLabel)
                    .addComponent(gameIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatIDLabel)
                    .addComponent(seatIDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectionLabel)
                    .addComponent(sectionText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceID)
                    .addComponent(priceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(updateSeatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(updateButton)
                .addGap(21, 21, 21))
        );

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(updateSeatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(270, 270, 270))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(backButton)
                        .addGap(57, 57, 57))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(updateSeatsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // Updates the seats in the database
        gameId = gameIDText.getText();
        seatId = seatIDText.getText();
        section = sectionText.getText();
        price = priceText.getText();
        status = statusText.getText();
        // Checks if any of the text fields are empty. If the are, it will print an error message
        if (gameId.isEmpty() || seatId.isEmpty() || section.isEmpty() || price.isEmpty() || status.isEmpty()){
            errorMsg.setText("One or more input fields are empty");
        }
        // If the text fields are not empty, the seats will be upated to the data base
        else{
            try {
                Admin admin = new Admin();
                admin.updateSeat(Integer.parseInt(gameId), Integer.parseInt(seatId), section, Integer.parseInt(price), status);
                AdminSignedInHomepage adminSignedInHomePage = new AdminSignedInHomepage();
                adminSignedInHomePage.setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(AdminSeating.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // Redirect back to AdminSignedInHomepage page
        AdminSignedInHomepage adminSignedInHomepageFrame = new AdminSignedInHomepage();
        adminSignedInHomepageFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminSeating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminSeating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminSeating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminSeating.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminSeating().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel banner;
    private javax.swing.JLabel creationNation;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JLabel gameIDLabel;
    private javax.swing.JTextField gameIDText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel priceID;
    private javax.swing.JTextField priceText;
    private javax.swing.JLabel seatIDLabel;
    private javax.swing.JTextField seatIDText;
    private javax.swing.JLabel sectionLabel;
    private javax.swing.JTextField sectionText;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField statusText;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel updateSeatsLabel;
    private javax.swing.JPanel updateSeatsPanel;
    // End of variables declaration//GEN-END:variables
}
