/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Payment extends javax.swing.JFrame {

    private int game_id;
    private int seat_id;
    private double priceValue;
    private double totalPrice;
    private String username;

    /**
     * Creates new form Payment. Users can enter their credit card information to make their purchase
     */
    public Payment() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }
    
    public Payment(String username) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        this.username = username;
    }
    
    public Payment(double price, String username) {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        this.username = username;
        priceValue = price;
        displayAmount.setText(Double.toString(priceValue));
    }
    
    public Payment(int game_id, int seat_id, double price, String username) throws SQLException{
        initComponents();
        getContentPane().setBackground(Color.WHITE);
        this.game_id = game_id;
        this.seat_id = seat_id;
        this.priceValue = price;
        this.username = username;
        // Get total of tickets from purchase data base
        ShoppingCart cart = new ShoppingCart(username);
        totalPrice = cart.getTotalCart(username);
        displayAmount.setText(Double.toString(totalPrice));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentPanel = new javax.swing.JPanel();
        paymentLabel = new javax.swing.JLabel();
        cardHolderName = new javax.swing.JLabel();
        cardNumber = new javax.swing.JLabel();
        expirationDate = new javax.swing.JLabel();
        securityCode = new javax.swing.JLabel();
        cardHolderNameText = new javax.swing.JTextField();
        cardNumberText = new javax.swing.JTextField();
        expirationDateText = new javax.swing.JTextField();
        securityCodeText = new javax.swing.JTextField();
        errorMsg = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        eventName = new javax.swing.JTextField();
        checkout = new javax.swing.JButton();
        totalAmount = new javax.swing.JLabel();
        displayAmount = new javax.swing.JLabel();
        banner = new javax.swing.JPanel();
        creationNation = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1110, 700));
        setSize(new java.awt.Dimension(1110, 700));

        paymentPanel.setBackground(new java.awt.Color(255, 255, 255));
        paymentPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        paymentLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        paymentLabel.setText("Payment");

        cardHolderName.setText("Cardholder name:");

        cardNumber.setText("Card number:");

        expirationDate.setText("Expiration date (MMYY):");

        securityCode.setText("Security code:");

        cardHolderNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardHolderNameTextActionPerformed(evt);
            }
        });

        errorMsg.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout paymentPanelLayout = new javax.swing.GroupLayout(paymentPanel);
        paymentPanel.setLayout(paymentPanelLayout);
        paymentPanelLayout.setHorizontalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(paymentLabel))
                    .addGroup(paymentPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardHolderName)
                            .addComponent(cardNumber)
                            .addComponent(expirationDate)
                            .addComponent(securityCode)
                            .addComponent(errorMsg))
                        .addGap(19, 19, 19)
                        .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cardNumberText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(expirationDateText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(securityCodeText, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paymentPanelLayout.createSequentialGroup()
                                .addComponent(cardHolderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        paymentPanelLayout.setVerticalGroup(
            paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paymentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paymentLabel)
                .addGap(12, 12, 12)
                .addComponent(errorMsg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardHolderName)
                    .addComponent(cardHolderNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expirationDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(expirationDate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paymentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(securityCodeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(securityCode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        summaryPanel.setBackground(new java.awt.Color(255, 255, 255));
        summaryPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        eventName.setBorder(null);
        eventName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventNameActionPerformed(evt);
            }
        });

        checkout.setText("Checkout");
        checkout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkoutActionPerformed(evt);
            }
        });

        totalAmount.setText("Total (no refunds):");

        displayAmount.setText("(total amount)");

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(totalAmount))
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                        .addComponent(checkout)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                        .addComponent(displayAmount)
                        .addGap(24, 24, 24))))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalAmount)
                    .addComponent(displayAmount))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eventName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(checkout)
                .addContainerGap())
        );

        banner.setBackground(new java.awt.Color(8, 52, 108));

        creationNation.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        creationNation.setForeground(new java.awt.Color(255, 255, 255));
        creationNation.setText("SoftwareCreationNation");

        jLabel5.setIcon(new javax.swing.ImageIcon("/Users/helentran/NetBeansProjects/GameArenaSys/Images/LogoBanner.png")); // NOI18N

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(creationNation)
                .addContainerGap(712, Short.MAX_VALUE))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bannerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(bannerLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(creationNation)))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(paymentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(paymentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(summaryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventNameActionPerformed
        
    }//GEN-LAST:event_eventNameActionPerformed
    //Check if string only contains letters
    private boolean checkLetters(String str){
        boolean allLetters = true;
        for (int i = 0; i < str.length(); i++){
            if(!Character.isLetter(str.charAt(i)) && str.charAt(i) != ' '){
                allLetters = false;
                break;
            }
        }
        return(allLetters);
    }
    //Check if string only contains digits
    private boolean checkDigits(String strInt){
        boolean allDigits = true;
        for (int i = 0; i < strInt.length(); i++){
            if(!Character.isDigit(strInt.charAt(i))){
                allDigits = false;
                break;
            }
        }
        return(allDigits);
    }
    
    private void checkoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkoutActionPerformed
        // Check if the inputs are valid
        String cardHolderName = cardHolderNameText.getText();
        String cardNumber = cardNumberText.getText();
        String expirationDate = expirationDateText.getText();
        String securityCode = securityCodeText.getText();
        
        //Check if name only contains letters
        boolean vaildName = checkLetters(cardHolderName);
        
        // Check if it only contains digits
        boolean validNumber = checkDigits(cardNumber);
        boolean validExpDate = checkDigits(expirationDate);
        boolean validSecurity = checkDigits(securityCode);
        
        // Check for appropriate length
        boolean validNameLen = cardHolderName.length() > 1;
        boolean validNumberLen = cardNumber.length() == 16;
        boolean validExpDateLen = expirationDate.length() == 4;
        boolean validSecurityLen = securityCode.length() == 3;
        
        
        if (vaildName && validNameLen && validNumber && validNumberLen && validExpDate && validExpDateLen && validSecurity && validSecurityLen){
            try {
                // Redirect to purchase page
                Confirmation confirmationFrame = new Confirmation(game_id, seat_id, priceValue, username, totalPrice);
                confirmationFrame.setVisible(true);
                this.dispose();
            } catch (SQLException ex) {
                Logger.getLogger(Payment.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            errorMsg.setText("Error");
        }
    }//GEN-LAST:event_checkoutActionPerformed

    private void cardHolderNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardHolderNameTextActionPerformed

    }//GEN-LAST:event_cardHolderNameTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JLabel cardHolderName;
    private javax.swing.JTextField cardHolderNameText;
    private javax.swing.JLabel cardNumber;
    private javax.swing.JTextField cardNumberText;
    private javax.swing.JButton checkout;
    private javax.swing.JLabel creationNation;
    private javax.swing.JLabel displayAmount;
    private javax.swing.JLabel errorMsg;
    private javax.swing.JTextField eventName;
    private javax.swing.JLabel expirationDate;
    private javax.swing.JTextField expirationDateText;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JLabel securityCode;
    private javax.swing.JTextField securityCodeText;
    private javax.swing.JPanel summaryPanel;
    private javax.swing.JLabel totalAmount;
    // End of variables declaration//GEN-END:variables
}
