/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Game;
import java.awt.Component;
import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.table.TableCellRenderer;

public class SchedulePage extends javax.swing.JFrame {
    
    public String username;

    /**
     * Creates new form Schedule
     */
    public SchedulePage() {
        initComponents();
        //load the games from the database for display
        schedule.loadGames();
        //display the games on the table
        fillTable();
        GridLayout grid = new GridLayout(10, 1);
        grid.setVgap(20);
        ticketBtns = new JPanel(grid);
    }
    
    public SchedulePage(String username) {
        initComponents();
        this.username = username;
        //load the games from the database for display
        schedule.loadGames();
        //display the games on the table
        fillTable();
        GridLayout grid = new GridLayout(10, 1);
        grid.setVgap(20);
        ticketBtns = new JPanel(grid);
    }
    
    Homepage homeP = new Homepage();
    Schedule schedule = new Schedule();
    
    @SuppressWarnings("empty-statement")
    public void fillTable()
    {
        //store the table columns
        String columns[] = {"Date", "Time", "Teams (Home vs Away)"};
        
        ArrayList<Game> games = schedule.getGames();
        
        //put all the games into a 2D array, upload that to the table on the gui
        int rows = games.size();
        Object sched[][] = new Object[rows][3];
        
        for (int i = 0; i < rows; i++)
        {
            for (int j = 0; j < 4; j++)
            {
                if (j == 0)
                    sched[i][j] = Integer.toString(games.get(i).date);
                else if (j == 1)
                    sched[i][j] = Integer.toString(games.get(i).time);
                else if (j == 2)
                    sched[i][j] = games.get(i).getName();
                else
                    ticketBtns.add(new JLabel("Email"));
            }
        }
        
        //update the table
        DefaultTableModel model = new DefaultTableModel(sched, columns);
        scheduleTable.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bannerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoLbl1 = new javax.swing.JLabel();
        homepageBtn = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        sortDateBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();
        ticketBtns = new javax.swing.JPanel();
        viewTixGame1 = new javax.swing.JButton();
        viewTixGame2 = new javax.swing.JButton();
        viewTixGame3 = new javax.swing.JButton();
        viewTixGame4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bannerPanel.setBackground(new java.awt.Color(0, 51, 102));
        bannerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SoftwareCreationNation");

        homepageBtn.setBackground(new java.awt.Color(204, 204, 204));
        homepageBtn.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        homepageBtn.setForeground(new java.awt.Color(255, 255, 255));
        homepageBtn.setText("Homepage");
        homepageBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        homepageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logoLbl1)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homepageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerPanelLayout.createSequentialGroup()
                .addGroup(bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bannerPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoLbl1))
                    .addGroup(bannerPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(bannerPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(homepageBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
        );

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        sortDateBtn.setBackground(new java.awt.Color(204, 204, 204));
        sortDateBtn.setForeground(new java.awt.Color(0, 51, 102));
        sortDateBtn.setText("Sort by Date");
        sortDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortDateBtnActionPerformed(evt);
            }
        });

        scheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Date", "Time", "Teams (Home vs Away)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scheduleTable.setRowHeight(45);
        jScrollPane1.setViewportView(scheduleTable);

        ticketBtns.setBackground(new java.awt.Color(255, 255, 255));

        viewTixGame1.setText("View Tickets");
        viewTixGame1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTixGame1ActionPerformed(evt);
            }
        });

        viewTixGame2.setText("View Tickets");
        viewTixGame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTixGame2ActionPerformed(evt);
            }
        });

        viewTixGame3.setText("View Tickets");
        viewTixGame3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTixGame3ActionPerformed(evt);
            }
        });

        viewTixGame4.setText("View Tickets");
        viewTixGame4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTixGame4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ticketBtnsLayout = new javax.swing.GroupLayout(ticketBtns);
        ticketBtns.setLayout(ticketBtnsLayout);
        ticketBtnsLayout.setHorizontalGroup(
            ticketBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBtnsLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(ticketBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewTixGame4)
                    .addComponent(viewTixGame2)
                    .addComponent(viewTixGame1)
                    .addComponent(viewTixGame3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ticketBtnsLayout.setVerticalGroup(
            ticketBtnsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ticketBtnsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(viewTixGame1)
                .addGap(18, 18, 18)
                .addComponent(viewTixGame2)
                .addGap(18, 18, 18)
                .addComponent(viewTixGame3)
                .addGap(18, 18, 18)
                .addComponent(viewTixGame4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(1277, Short.MAX_VALUE)
                .addComponent(sortDateBtn)
                .addGap(19, 19, 19))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ticketBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sortDateBtn)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(69, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(ticketBtns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bannerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sortDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortDateBtnActionPerformed
        // call the sorting method for sort by date
        schedule.sortedSchedule();
        fillTable();
    }//GEN-LAST:event_sortDateBtnActionPerformed

    private void homepageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageBtnActionPerformed
        // TODO add your handling code here:
        homeP.setVisible(rootPaneCheckingEnabled);
        setVisible(false);
    }//GEN-LAST:event_homepageBtnActionPerformed

    private void viewTixGame1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTixGame1ActionPerformed
        try {
            // ADD: GO TO THE TICKET PAGE FOR THIS GAME
            Seating game1Seating = new Seating(1, username);
            game1Seating.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SchedulePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewTixGame1ActionPerformed

    private void viewTixGame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTixGame2ActionPerformed
        try {
            // ADD: GO TO THE TICKET PAGE FOR THIS GAME
            Seating game2Seating = new Seating(2, username);
            game2Seating.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SchedulePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewTixGame2ActionPerformed

    private void viewTixGame3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTixGame3ActionPerformed
        try {
            // ADD: GO TO THE TICKET PAGE FOR THIS GAME
            Seating game3Seating = new Seating(3, username);
            game3Seating.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SchedulePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewTixGame3ActionPerformed

    private void viewTixGame4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTixGame4ActionPerformed
        try {
            // ADD: GO TO THE TICKET PAGE FOR THIS GAME
            Seating game4Seating = new Seating(4, username);
            game4Seating.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(SchedulePage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_viewTixGame4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SchedulePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SchedulePage().setVisible(true);
            }
        });
        
        try{
            Class.forName("org.sqlite.JDBC");
        }
        catch(Exception e)
        {
            System.err.println(e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JButton homepageBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLbl1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTable scheduleTable;
    private javax.swing.JButton sortDateBtn;
    private javax.swing.JPanel ticketBtns;
    private javax.swing.JButton viewTixGame1;
    private javax.swing.JButton viewTixGame2;
    private javax.swing.JButton viewTixGame3;
    private javax.swing.JButton viewTixGame4;
    // End of variables declaration//GEN-END:variables
}


